[project]
name = "rl-fastapi-app"
version = "0.1.0"
requires-python = "==3.12.6"

dependencies = [
    "fastapi==0.115.6",   # FastAPI itself
    "uvicorn==0.35.0",    # ASGI server
    "ijson==3.4.0",       # streaming JSON parser
    "python-dotenv==1.0.1", # for .env config if needed
]